# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - deploy-namespace.yaml
  - deployment.yaml
  - service.yaml

# namespace to deploy all Resources to
namespace: my-namespace

# labels added to all Resources
commonLabels:
  env: test
