# deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-namespace
spec:
  selector:
    app: nginx
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  type: LoadBalancer
