
# Only on Development we build snapshots
on:
  push:
    branches:
      - development
      - main

env:
  PROJECT_NAME: static-http
  DOCKER_IMAGE_NAME: "nginx"

jobs:
  
  #############################################
  # Build App and Docker Image
  #############################################
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      deployments: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
  
      - name: Github Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: publisher
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          # Disabling provenance check due to https://community.fly.io/t/images-built-with-the-latest-docker-buildx-and-or-github-actions-work-again/10816
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          file: build/docker/app/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}
          push: true
